name = "xml"
display_name = "XML Language Support"
description = "LSP formatting and validation for XML"
version = "1.0.0"
file_extensions = [".xml", ".xsd", ".xsl", ".xslt", ".svg", ".pom"]
language_ids = ["xml", "xsl"]
workspace_markers = ["pom.xml"]

[lsp]
binary = "lemminx"
install = ""
fallback_binaries = []
args = []

scripts = []
